### ISSUE TITLE
Handle inconsistent states across different instances of the history database [N2]

### ISSUE THREAD

**Issue by venuslimm** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#163]
Inconsistent states occurs when there are multiple mysql/history database instances (history service) but only the local history database is updated when the local app deletes a question. Other mysql instances (history databases) will not be updated since mysql runs locally.

Possible solution: Whenever the history service starts up, it will check if all the questions in the history service exist in the question service. If any questions doesn't exist, delete those rows. This might be solvable using docker when history service starts up.

**Comment by lhy-hoyin** [comment]
This has been resolved by converting MySQL to MongoDB for user DB.
