### ISSUE TITLE
Demote button does not actually demote admin to user

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#173]
"Demote to normal user" button does not work as expected.
Toast is generated to indicate success, but DB is not updated.

To reproduce error:

Acct 1: admin (isAdministrator=1)
Acct 2: user (isAdministrator=1)

1. Log into Acct 1

2. Go to Manage User Profiles

3. Under Acct 2 (user), click `Demote to normal user`
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/assets/88828097/81398f82-9f5d-471e-b95e-b89412cbdb96)

4. Confirmation popup appears, click `Yes` to confirm
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/assets/88828097/37482619-ddaf-414b-8cd8-aea7d4323da4)

6. Success toast appears: "User has neem demoted to a normal user successfully!"
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/assets/88828097/3630b137-7509-4f6d-a81f-f2a9282ba431)

8. Check SQL Database via CLI
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/assets/88828097/b8e96e60-a5b1-4fb4-9a19-39a52f8dcbb7)

9. Still showing Acct 2 as `isAdministrator=1`

**Comment by venuslimm** [comment]
Resolved in #169
