### ISSUE TITLE
/auth/generate loads forever when missing parameters

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#174]
When POST to `http://localhost:5001/auth/generate` using
```json
{
    "isMaintainer": "1" 
}
```
or
```json
{
    "userId": "1"
}
```
the request doesn't get a response.

Expected behaviour:
POST request returns with error complaining about missing parameters

**Comment by venuslimm** [comment]
Unable to reproduce bug
