### ISSUE TITLE
Repeated toggling of user role doesn't update

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#176]
I tried to toggle user status a few time via `/user/toggle-user-role`/

It seems to toggle the first time, but then stops working the 2nd time onwards.

**Comment by lhy-hoyin** [comment]
Might be the bug origin of #173.

Check if you are you updating the local (i.e cookie's) userId after toggling?

**Comment by venuslimm** [comment]
Resolved in #169
