### ISSUE TITLE
Matching Service: improve join room mechanism

### ISSUE THREAD

**Issue by lhy-hoyin** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#179]
1. Button to join back room via id
(maybe hide room ID, but have it stored in cookies etc -> prevent something like [zoom bombing](https://www.dcc.edu/administration/offices/information-technology/zoom/zoom-bombing.aspx#:~:text=In%20a%20typical%20Zoom%2Dbombing,the%20shutdown%20of%20the%20session.))

2. Enable single user to create room (enable friend to join via room id)

**Comment by JrmCkh** [comment]
Closes as rejoin room is implemeted on #248 

Single user room creation is not implemented
