### ISSUE TITLE
Merge assignment 1 into assignment 2

### ISSUE THREAD

**Issue by venuslimm** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#52]
To fulfill this requirement for assignment 2: `(b) In this part, you will enhance Question Repository created in Assignment 1 by designing APIs for the CRUD operations and maintaining question records in a NoSQL database such as MongoDB.`, which is currently done in assignment 1 repo.

**Comment by cadencjk** [comment]
Should merge assignment-1 to dev branch first, then from dev to assignment-2

**Comment by cadencjk** [comment]
Can merge once PR #53 is completed
