### ISSUE TITLE
Fix bug where description size is too large

### ISSUE THREAD

**Issue by cadencjk** [CS3219-AY2324S1/ay2324s1-course-assessment-g32#80]
Currently it throws an error in the console, but Toast does not show up anything

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g32/assets/50315976/b76520c8-8e7c-4cae-a289-6d772896b206)

**Comment by lhy-hoyin** [comment]
Issue seems to be resolved. Re-open issue if necessary.
